import torch as t

EMPTY = 0
PAWN, PASSANT_PAWN, UNMOVED_ROOK, MOVED_ROOK, KNIGHT = 1, 2, 3, 4, 5
LIGHT_BISHOP, DARK_BISHOP, QUEEN, UNMOVED_KING, MOVED_KING = 6, 7, 8, 9, 10
OPPONENT_OFFSET = 10


# fmt: off
DEFAULT_STARTING_BOARD = t.tensor([
    [UNMOVED_ROOK, KNIGHT, LIGHT_BISHOP, QUEEN, UNMOVED_KING, DARK_BISHOP, KNIGHT, UNMOVED_ROOK],
    [PAWN, PAWN, PAWN, PAWN, PAWN, PAWN, PAWN, PAWN],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET, PAWN+OPPONENT_OFFSET],
    [UNMOVED_ROOK+OPPONENT_OFFSET, KNIGHT+OPPONENT_OFFSET, LIGHT_BISHOP+OPPONENT_OFFSET, QUEEN+OPPONENT_OFFSET, UNMOVED_KING+OPPONENT_OFFSET, DARK_BISHOP+OPPONENT_OFFSET, KNIGHT+OPPONENT_OFFSET, UNMOVED_ROOK+OPPONENT_OFFSET]
])
# fmt: on